export const USER_PROFILE = 'Profile';
export const REGISTRATION = 'Registration';
export const HOME_NAVIGATION = 'Accueil';
export const NOTIFICATIONS = 'Notifications';
export const SAVED_INFOS = 'A lire plus tard';
export const ABOUT = 'A propos de nous';
export const INFOS_DETAILS = 'Details';
export const TOP_TAB_NAVIGATION = 'Home';
export const POLITIQUE = 'Politique'
export const ECONOMIE = 'économie';
export const EDUCATION = 'éducation';
export const INTERNATIONAL = 'International';
export const COMMUNIQUE = 'Communiqué';
export const SANTE = 'Santé';
export const SPORT = 'Sport';
export const CULTURE = 'Culture';
export const SECURITE = 'Sécurité';
export const SOCIETE = 'Société';
export const A_LA_UNE = 'A la une';
export const A_PROPOS_DE_NOUS = 'A propos de nous';
export const LA_TEAM = "L'équipe";
export const SIGN_UP = 'Inscription';
export const CONFIRMATION = 'Confirmation';
export const NOTIFICATIONSDISABLED = 'Notifications';
export const ONBOARDING = 'Onboarding'
